language: cpp
compiler: clang
before_install: sudo apt-get update -qq
install: sudo apt-get install -y llvm-3.4-dev libboost1.48-all-dev gfortran
script: ./configure --with-llvm=/usr/bin/llvm-config-3.4 && make && make test
