sudo: false
language: cpp
compiler:
        - clang
        - gcc
matrix:
  allow_failures:
    - compiler: gcc
install:
        - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
addons:
  apt:
        sources:
        - ubuntu-toolchain-r-test
        - boost-latest
        packages:
        - llvm-3.4-dev
        - libboost1.55-all-dev
        - gcc-4.8
        - g++-4.8
        - gfortran
script:
        - tools/rsync-recommended
        - ./configure
          --enable-llvm-jit=yes
          --with-llvm=/usr/bin/llvm-config-3.4
        - travis_wait 60 make -j 2
        - travis_wait 60 make -j 2 check
