language: cpp
compiler:
        - clang
        - gcc
matrix:
  allow_failures:
    - compiler: gcc
before_install: sudo apt-get update -qq
install:
        - sudo apt-get install -y
          llvm-3.4-dev
          libboost1.48-all-dev
          gfortran
script:
        - tools/rsync-recommended
        - ./configure
          --enable-llvm-jit=yes
          --enable-byte-compiled-packages=no
          --with-llvm=/usr/bin/llvm-config-3.4
        - travis_wait 60 make -j 2
        - travis_wait 60 make -j 2 check
